ChestXray_data_processing_config:
  processed_data_path: './artifacts/data/processed/caption/ChestXray'
  images_base_path: './artifacts/data/raw/images/ChestXray'
  projections_path: './artifacts/data/raw/caption/ChestXray/indiana_projections.csv'
  reports_path: './artifacts/data/raw/caption/ChestXray/indiana_reports.csv'
  processed_data_output_path: './artifacts/data/processed/caption/ChestXray/'
  processed_first: False

ROCO_data_processing_config:
  raw_data_path: './artifacts/data/raw/caption/ROCO/'
  processed_data_path: './artifacts/data/processed/caption/ROCO'
  images_base_path: './artifacts/data/raw/images/ROCO'


model_config:
  vocab_size: 50257
  embed_dim: 768
  num_heads: 12
  seq_len: 1024
  depth: 12
  attention_dropout: 0.1
  residual_dropout: 0.1
  mlp_ratio: 4
  mlp_dropout: 0.1
  emb_dropout: 0.1
  fine_tune: True
  encoder_type: resnet50 #resnet50

train_config:
  training_params:
    epochs: 20
    learning_rate: 0.0001
    device: cuda
    batch_size: 4
    freeze_epochs_gpt: 1
    freeze_epochs_all: 2
    general_specific_fine_tuning: True

  ChestXray:
    train_data_path: './artifacts/data/processed/caption/ChestXray/train.csv'
    val_data_path: './artifacts/data/processed/caption/ChestXray/validation.csv'
    test_data_path: './artifacts/data/processed/caption/ChestXray/test.csv'
    training_data_path: './artifacts/data/processed/caption/ChestXray/dataProcessed.csv'
    trained_model_output_folder_path: './artifacts/models/ChestXray/'
    roco_trained_model_path: './artifacts/models/ROCO/trainedModel.pt'
    trained_model_output_path: './artifacts/models/ChestXray/trainedModel.pt'
    metrics_path: './artifacts/metrics/ChestXray/train/trainingMetrics.csv'
    metrics_folder_path: './artifacts/metrics/ChestXray/train/'
    processed_data_path: './artifacts/data/processed/caption/ChestXray'

  ROCO:
    train_data_path: './artifacts/data/processed/caption/ROCO/train.csv'
    val_data_path: './artifacts/data/processed/caption/ROCO/validation.csv'
    test_data_path: './artifacts/data/processed/caption/ROCO/test.csv'
    trained_model_output_folder_path: './artifacts/models/ROCO/'
    trained_model_output_path: './artifacts/models/ROCO/trainedModel.pt'
    metrics_path: './artifacts/metrics/ROCO/train/trainingMetrics.csv'
    metrics_folder_path: './artifacts/metrics/ROCO/train/'
    processed_data_path: './artifacts/data/processed/caption/ROCO'

inference_config:
  trained_model_path: './artifacts/models/second_stage_model.pth'
  inference_data_path: './artifacts/data/processed/caption/ChestXray/test.csv'
  metrics_path: './artifacts/metrics/test/ChestXray/testMetrics.csv'
  metrics_folder_path: './artifacts/metrics/test/ChestXray/'
  device: cuda
  temperature: 1.0

